### ISSUE TITLE
Slight difference in generator algorithm?

### ISSUE THREAD

**Issue by roytanck** [heyvito/kabegami#1]
https://github.com/heyvito/kabegami/blob/23631c6129f388514253655483e81c2130500e49/Kabegami/Generator.swift#L58

In the Javascript version, I'm using a `<=` to make sure the wave reaches the right side of the screen. Basically,, `i` should run from 0 to (and including) segments.

On a friend's Mac, I noticed some weirdness, on the right side of some wallpapers. I'm not familiar with Swift, but thought this might perhaps be the cause.

**Comment by heyvito** [comment]
Nice catch! That's indeed incorrect!
I'll issue an update ASAP.

I also noticed it generates the whole thing upside-down, perhaps. Since AppKit origin is bottom-left instead of top-left like Canvas. I still need to figure this one out...

**Comment by heyvito** [comment]
Released v1.1 with that fix! Thank you @roytanck! ♥️
